services:
  voiceassistant:
    build:
      context: .
    container_name: voiceassistant
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      OPENAI_API_KEY: ${OPENAI_API_KEY}
